FROM node:16-alpine as build

WORKDIR /app

RUN apk update && apk add --no-cache \
    python3 \
    make \
    g++ \
    bash

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN yarn build && ls -la ./dist

RUN ls -la /app/dist


#---

FROM node:alpine

WORKDIR /app

ENV NODE_ENV=production

RUN apk update && apk add --no-cache \
    python3 \
    make \
    g++ \
    bash

COPY package.json .
COPY yarn.lock .
COPY ormconfig.js .

RUN yarn install --production

COPY --from=build /app/dist ./dist

EXPOSE 5000

ENTRYPOINT [ "yarn", "start:prod" ]